-- 코드를 입력하세요
# SELECT CAR_ID, ROUND(AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE)), 1) AS AVERAGE_DURATION
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# HAVING ROUND(AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE)), 1) >= 7
# ORDER BY ROUND(AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE)), 1) DESC, CAR_ID DESC;

# 4 44 / 3 = 14.66
# 29 107 / 4 = 26.75
SELECT CAR_ID, ROUND(AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE) +1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;