SELECT FLAVOR FROM 
(
    SELECT t1.FLAVOR, SUM(t1.TOTAL_ORDER) AS ORDERS
    FROM FIRST_HALF t1
    INNER JOIN JULY t2
    ON t1.FLAVOR = t2.FLAVOR
    GROUP BY t1.FLAVOR
    ORDER BY ORDERS DESC
    LIMIT 3
) t3;
